export const CHANGE_INPUT_VALUE = "CHANGE_INPUT_VALUE";
export const ADD_LIST_ITEM = "ADD_LIST_ITEM";
export const DELETE_LIST_ITEM = "DELETE_LIST_ITEM";
export const CHANGE_BUTTON_ITEM = "CHANGE_BUTTON_ITEM";
export const CHANGE_LIST_DATA = "CHANGE_LIST_DATA";
export const CHANGE_ITEM_STATE = "CHANGE_ITEM_STATE";